### ISSUE TITLE
Feature Request: Return Status Code in Result

### ISSUE THREAD

**Issue by RKTMN** [edganiukov/fcm#10]
Hello! I am trying to parse the response I get from this FCM client into my own Response struct, which includes an http status code. According to the FCM docs on the error response codes, some Error types that you have, notably ErrUnavailable and ErrInternalServerError, could correspond to both a 200 or a 5xx. 

Since you have direct access to the status code returned in the http response, I was hoping you could make the modification to your project to return the http status code in your Result struct as well. Less importantly, this will also save us from having to resort to switching on the messages of your errors in order to map them to an http status code.

**Comment by edganiukov** [comment]
Hi, sure, could be useful. But I have added HTTP status code to Response object, not Result.
Here is PR https://github.com/edganiukov/fcm/pull/11
