### ISSUE TITLE
No way to send to a topic ?

### ISSUE THREAD

**Issue by agnivade** [edganiukov/fcm#12]
The message struct https://godoc.org/github.com/edganiukov/fcm#Message is missing a topic field. There is no way to send a message to a topic directly except through a condition.

Here is the resource representation - https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages.

Please add the topic field.

**Comment by edganiukov** [comment]
Hi @agnivade ,
This lib implements a legacy API - https://firebase.google.com/docs/cloud-messaging/http-server-ref
To send to a topic, you should use the same field (`Token` in this case, which then converted to `to` field in json):
> The value can be a device's registration token, a device group's notification key, or a single topic (prefixed with /topics/). To send to multiple topics, use the condition parameter.

**Comment by agnivade** [comment]
Ah thank you. Perhaps, you can add this to the documentation.
