### ISSUE TITLE
Valid payload produces error

### ISSUE THREAD

**Issue by ghost** [edganiukov/fcm#5]
Example from the documentation: https://firebase.google.com/docs/cloud-messaging/ios/topic-messaging#http_post_request

This payload should be accepted by the library, but it is not:

```json
{
  "condition": "'dogs' in topics || 'cats' in topics",
  "data": {
    "message": "This is a Firebase Cloud Messaging Topic Message!",
   }
}
```

**Comment by edganiukov** [comment]
Thanks for the issue. This PR #6 should fix it.

**Comment by edganiukov** [comment]
Is error still occurs? If not, I am gonna close this issue
