### ISSUE TITLE
 syntax error: unexpected semicolon or newline, expecting comma or }

### ISSUE THREAD

**Issue by k0fi** [edganiukov/fcm#7]
Hi,
I get error while I try the sample code

` controller/firebase.go:38: syntax error: unexpected semicolon or newline, expecting comma or }
`

The relevant code:

```
	msg := &fcm.Message{
		Token: "myDeviceToken",
		Data: map[string]interface{}{
			"foo": "bar",
		} // <- Line 38
	}
```

When I add a comma after the } at line 38, I get this instead:

`controller/firebase.go:41: multiple-value "github.com/edganiukov/fcm".NewClient() in single-value context
`

What's wrong here? How to fix it?

**Comment by edganiukov** [comment]
Hi @k0fi, there is a small typo - should be a comma after `}`
```
msg := &fcm.Message{
		Token: "myDeviceToken",
		Data: map[string]interface{}{
			"foo": "bar",
		},
	}
```

And `NewClient` returns error, so: 
```
client, err := fcm.NewClient("sample_api_key")
if err != nil {
  log.Fatal(err)
}
```

**Comment by lukibahr** [comment]
did you resolve this issue? I've got the same here: 

```go
	 login := Login{
	 	Action: "login",
	 	Param {
	 		Apikey: c.Apikey,
	 		Apipassword: c.Apipassword,
	 		Customernumber: c.Customernumber,
		 } //<-- when I add the comma here, it says mixture of field:value and value initializers
		}
```
