### ISSUE TITLE
'factor' unused in retry.

### ISSUE THREAD

**Issue by aravindc26** [edganiukov/fcm#8]
I find that `factor` in the retry utility is not used anywhere.

https://github.com/edganiukov/fcm/blob/a59832c40f352a6780ce9fb7e18d815d57ac9aa3/retry.go#L11

I believe it should have been used here while calculating `backoff`

https://github.com/edganiukov/fcm/blob/a59832c40f352a6780ce9fb7e18d815d57ac9aa3/retry.go#L27

**Comment by edganiukov** [comment]
Yes, I had a plan to use it, but in the end is was not needed.
