### ISSUE TITLE
Update Handling of DeviceUnregistered Errors

### ISSUE THREAD

**Issue by RKTMN** [edganiukov/fcm#9]
7 days ago, FCM updated their SDK to equate some or all 404s with DeviceUnregistered errors, in an attempt to map server errors to client ones. This library should be updated to handle the new cases of DeviceUnregistered results that are returned from FCM

**Comment by edganiukov** [comment]
Seems like there is a new version of API - https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
I will take a look on weekend. Thanks for the information.

**Comment by RKTMN** [comment]
Thank you for taking a look! Is there any update after you have had some time to look at their new version of the API?

**Comment by edganiukov** [comment]
Hi @RKTMN , yes I had a look and I would say that the new API is completely different, especially  authN/authZ part. But, if I understand correct, legacy HTTP API is still supported and no changes there, so this lib should work.

**Comment by RKTMN** [comment]
We were getting 404's from this FCM client for about an hour the morning that I posted this issue. However, after this much time of that problem not reoccurring, we believe that it was a temporary problem on FCM's end that's been fixed. Should be fine to close this issue now:
